language: node_js
node_js:
  - "4.0"
before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install wine nsis -y
script: npm run ci
deploy:
  provider: releases
  api_key:
    secure: bs47IeoW/HhSC+4TgUu18KfFmHYXcxzEKBVhL1meRx+3kxpHJM58pfX+UlRdCWIs0P0/+OgwHaC1oQ8rT/v1fk1k0s13u8WEUY1iA/+modvoFKl2Cn8JVxVhgx58nKDdTQD1tVhWhiJuP4+iwDo+fU0GoDsxl+tq8Sv5ODsI78g29sP/xrMrdvAUHvqw+zNaSnir2OGQi/yIVclYUcUE58GCcCp8yZRje6f01Jw5HMFSpeDu7qtQnUUHVOvgdyO1aBWvLWwwnrE2q/cCsS06FBR23x93TTsixLL1PXwiM4UBQHaSqWKRtuP7z0cVJ2ygzF6FnUVZeBurlZX0WVtjl/nGbRG3/XkQ9b6ovacRGX0lOiB93cDqzBUlBNOI0cMkUKiifi1NocRAmsj2p+oPDE10XGGaM34OYreeWK4IfT8VqYqtanB3jhjnvLQ0Z8i7KZOSu9foExBHZQ3rKSUtfMVdg3d97bqlqzRdT/qCCFuiXIQeInOFn3ay7IaI5/ogQoJgEr9OwT14KR1wCKF2V+c7MDcOQdIn/41i6BfqvF+5NE4PvAxOAvs3p3e+Rp3EaSa+m2lR7PrOepIcmxQEY+G5FZYmdw8WLy9gTEdJJR8Qum2Mc5NopXKngsgyPAOWcPJgHJE2BZqtBtNHk0b2av555QSr9Ikw/WuF72f7hXg=
  file: "electron/win/Trevarez Setup.exe"
  skip_cleanup: true
  on:
    tags: true
